server:
  port: 8081
spring:
  application:
    name: "customers"
  config:
    import: "optional:configserver:http://localhost:8082/"
  jpa:
    hibernate:
      ddl-auto: create
    show-sql: true
  profiles:
    active: "default"